In [3]:
import pandas as pd 
import requests

In [6]:

url = "https://active-jobs-db.p.rapidapi.com/active-ats"


headers = {
    "x-rapidapi-key": "4240baad36msh4bc732820db529dp1d8916jsn21b839efc351",
    "x-rapidapi-host": "active-jobs-db.p.rapidapi.com",
    "Content-Type": "application/json"
}

params = {
    "time_frame": "24h",
    "limit": "10",
    "offset": "0",
    "description_format": "text",
    "title": '"Data Engineer"',
    "location": '"United States" OR "United Kingdom"'
}

response = requests.get(url, headers=headers, params=params)

if response.status_code == 200:
    print("Success! JSON response:")
    print(response.json()) 
else:
    print(f"Error {response.status_code}: {response.text}")

Success! JSON response:

In [7]:
if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    display(df) 
else:
    print(f"Error {response.status_code}: {response.text}")

,id,date_posted,date_created,title,organization,organization_url,date_valid_through,locations,locations_alt,location_type,...,ai_core_responsibilities,ai_requirements_summary,ai_working_hours,ai_employment_type,ai_job_language,ai_visa_sponsorship,ai_keywords,ai_taxonomies_a,ai_education,description_text
0,2229498706,2026-06-28T00:00:00,2026-06-28T05:20:37.997439,Data Engineer,Overflow,https://www.overflow.co/,None,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,TELECOMMUTE,...,Architect and build the core data infrastructu...,Requires 5+ years of data engineering experien...,40,[FULL_TIME],English,False,"[Databricks, Unity Catalog, Delta Lake, AWS, S...","[Data & Analytics, Technology, Engineering, So...",None,"Who We Are\nOverflow is a Series C, growth-sta..."
1,2229270209,2026-06-27T21:25:37,2026-06-27T21:44:48.797036,Sr Data Engineer,BHE,https://fa-essf-saasfaprod1.fa.ocs.oraclecloud...,2026-07-27T00:00:00,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,,...,"Design, build, and maintain scalable data pipe...",Requires a bachelor's degree in a technical fi...,40,[FULL_TIME],English,True,"[Data Engineering, Azure, Azure Data Factory, ...","[Data & Analytics, Technology, Energy, Enginee...",[bachelor degree],"As a Sr Data Engineer, you will design, build,..."
2,2228674328,2026-06-27T00:00:00,2026-06-27T08:04:06.221257,Data Engineer / Cloud ETL Developer,General Dynamics Information Technology,,None,"[{'@type': 'Place', 'address': {'@type': 'Post...",[United States],None,...,"Design, develop, and implement complex ETL pro...",Requires a bachelor's degree in Computer Scien...,40,[FULL_TIME],English,False,"[Data Engineering, Cloud ETL, Python, SQL, AWS...","[Data & Analytics, Technology, Software, Engin...",[bachelor degree],Type of Requisition: Regular Clearance Level M...
3,2229488016,2026-06-26T00:00:00,2026-06-28T04:43:39.316282,Data Engineer II,Topgolf,,None,"[{'@type': 'Place', 'address': {'@type': 'Post...","[Dallas, United States]",TELECOMMUTE,...,"Design, build, and maintain scalable ETL/ELT d...",Requires 2+ years of experience in data engine...,40,[FULL_TIME],English,False,"[Sql, Python, Aws, Redshift, S3, Apache Airflo...","[Data & Analytics, Technology, Engineering, So...",None,"We are seeking a Data Engineer II to design, b..."
4,2228820476,2026-06-26T00:00:00,2026-06-27T11:21:42.278988,Lead Data Engineer,Capital One,,None,"[{'@type': 'Place', 'address': {'@type': 'Post...","[Richmond, VA, United States, McLean, VA, Camb...",None,...,"Design, develop, and implement robust cloud-ba...",Requires a Bachelor's degree with at least 4 y...,40,[FULL_TIME],English,False,"[Data Engineering, Big Data, Cloud Computing, ...","[Data & Analytics, Technology, Software, Engin...",[bachelor degree],Lead Data Engineer Do you love building and pi...
5,2228738639,2026-06-26T00:00:00,2026-06-27T09:14:00.096503,Lead Cloud Data Engineer - Multi-Cloud Data Pl...,U.S. Bank,,2026-06-29T00:00:00,"[{'@type': 'Place', 'address': {'@type': 'Post...","[Irving, TX, United States, Chicago, IL, Hopki...",None,...,"Design, build, and operate enterprise-grade da...",Requires a bachelor's degree and six to eight ...,40,[FULL_TIME],English,False,"[Azure Data Factory, Azure Data Lake Storage, ...","[Data & Analytics, Technology, Engineering, So...","[bachelor degree, postgraduate degree]","At U.S. Bank, we’re on a journey to do our bes..."
6,2228734887,2026-06-26T00:00:00,2026-06-27T09:11:39.347073,Data Engineer II,Lurie Children's Hospital,,None,"[{'@type': 'Place', 'address': {'@type': 'Post...","[Chicago, IL, United States]",None,...,The Data Engineer II implements and maintains ...,Requires 5+ years of hands-on experience in da...,40,[FULL_TIME],English,False,"[Data Engineering, SQL, Python, ETL, ELT, Data...","[Data & Analytics, Technology, Healthcare, Eng...",[bachelor degree],Ann & Robert H. Lurie Children’s Hospital of C...
7,2228737485,2026-06-25T00:00:00,2026-06-27T09:13:01.646219,"Associate Cloud Data Engineer ( SQL , Python ,...",CVS Health,,2026-06-30T00:00:00,"[{'@type': 'Place', 'address': {'@type': 'Post...","[Hartford, CT, United States]",TELECOMMUTE,...,Develop scalable data structures and pipelines...,"Requires 1+ years of experience with Python, S...",40,[FULL_TIME],English,False,"[Sql, Python, Etl, Cloud, Gcp, Azure, Aws, Had...","[Data & Analytics, Technology, Engineering, He...","[bachelor degree, postgraduate degree]",We’re building a world of health around every ...
8,2228732688,2026-06-25T00:00:00,2026-06-27T09:10:19.367873,Intermediate Data Engineer,Gordon Food Service,,None,"[{'@type': 'Place', 'address': {'@type': 'Post...","[Wyoming, MI, United States, Atlanta, GA]",None,...,Develop the GFS Data Platform including the da...,Requires experience in enterprise software dev...,40,[FULL_TIME],English,False,"[Data Lake, Enterprise Data Warehouse, Agile, ...","[Data & Analytics, Technology, Engineering, So...",None,Welcome to Gordon Food Service! We are excited...
9,2228612217,2026-06-24T18:17:47,2026-06-27T06:37:10.393694,Sr Data Engineer- Data Platform & AI Enablement,Citizens,https://hcgn.fa.us2.oraclecloud.com:443/hcmUI/...,2026-08-31T04:00:00,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,,...,Design and maintain scalable data pipelines to...,Requires 6-8+ years of experience in data engi...,40,[FULL_TIME],English,False,"[Data Engineering, Distributed Data Processing...","[Data & Analytics, Technology, Engineering, So...",[bachelor degree],SENIOR DATA ENGINEER – ENTERPRISE DATA ENABLEM...

In [8]:
df.head(5)

,id,date_posted,date_created,title,organization,organization_url,date_valid_through,locations,locations_alt,location_type,...,ai_core_responsibilities,ai_requirements_summary,ai_working_hours,ai_employment_type,ai_job_language,ai_visa_sponsorship,ai_keywords,ai_taxonomies_a,ai_education,description_text
0,2229498706,2026-06-28T00:00:00,2026-06-28T05:20:37.997439,Data Engineer,Overflow,https://www.overflow.co/,None,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,TELECOMMUTE,...,Architect and build the core data infrastructu...,Requires 5+ years of data engineering experien...,40,[FULL_TIME],English,False,"[Databricks, Unity Catalog, Delta Lake, AWS, S...","[Data & Analytics, Technology, Engineering, So...",None,"Who We Are\nOverflow is a Series C, growth-sta..."
1,2229270209,2026-06-27T21:25:37,2026-06-27T21:44:48.797036,Sr Data Engineer,BHE,https://fa-essf-saasfaprod1.fa.ocs.oraclecloud...,2026-07-27T00:00:00,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,,...,"Design, build, and maintain scalable data pipe...",Requires a bachelor's degree in a technical fi...,40,[FULL_TIME],English,True,"[Data Engineering, Azure, Azure Data Factory, ...","[Data & Analytics, Technology, Energy, Enginee...",[bachelor degree],"As a Sr Data Engineer, you will design, build,..."
2,2228674328,2026-06-27T00:00:00,2026-06-27T08:04:06.221257,Data Engineer / Cloud ETL Developer,General Dynamics Information Technology,,None,"[{'@type': 'Place', 'address': {'@type': 'Post...",[United States],None,...,"Design, develop, and implement complex ETL pro...",Requires a bachelor's degree in Computer Scien...,40,[FULL_TIME],English,False,"[Data Engineering, Cloud ETL, Python, SQL, AWS...","[Data & Analytics, Technology, Software, Engin...",[bachelor degree],Type of Requisition: Regular Clearance Level M...
3,2229488016,2026-06-26T00:00:00,2026-06-28T04:43:39.316282,Data Engineer II,Topgolf,,None,"[{'@type': 'Place', 'address': {'@type': 'Post...","[Dallas, United States]",TELECOMMUTE,...,"Design, build, and maintain scalable ETL/ELT d...",Requires 2+ years of experience in data engine...,40,[FULL_TIME],English,False,"[Sql, Python, Aws, Redshift, S3, Apache Airflo...","[Data & Analytics, Technology, Engineering, So...",None,"We are seeking a Data Engineer II to design, b..."
4,2228820476,2026-06-26T00:00:00,2026-06-27T11:21:42.278988,Lead Data Engineer,Capital One,,None,"[{'@type': 'Place', 'address': {'@type': 'Post...","[Richmond, VA, United States, McLean, VA, Camb...",None,...,"Design, develop, and implement robust cloud-ba...",Requires a Bachelor's degree with at least 4 y...,40,[FULL_TIME],English,False,"[Data Engineering, Big Data, Cloud Computing, ...","[Data & Analytics, Technology, Software, Engin...",[bachelor degree],Lead Data Engineer Do you love building and pi...

In [9]:
df.to_csv("active_jobs_data.csv", index=False)